name: Changelog

on:
  push:
    branches:
      - release/*
      - hotfix/*
  workflow_dispatch:

jobs:
  check-skip:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.check.outputs.should_skip }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check if the commit is a release PR
        id: check
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          if [[ $COMMIT_MSG == *"Merge pull request"* && $COMMIT_MSG == *"release-please--branches"* ]]; then
            echo "should_skip=true" >> "$GITHUB_OUTPUT"
          fi

  create-changelog:
    runs-on: ubuntu-latest
    needs: check-skip
    if: needs.check-skip.outputs.should_skip != 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Retrieve version from package.json
        id: retrieve_version
        run: |
          new_version=$(jq -r .version package.json)
          if [ -z "$new_version" ]; then
            echo "❌ version not found in package.json" >&2
            exit 1
          fi
          if ! echo "$new_version" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' > /dev/null; then
            echo "❌ version '$new_version' is not a valid semantic version (e.g., 1.2.3)" >&2
            exit 1
          fi
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      # - name: Set release version for changelog
      #   run: |
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #     git config --global user.name "github-actions[bot]"
      #     git commit --allow-empty -m "chore: release ${{ steps.retrieve_version.outputs.new_version }}" -m "Release-As: ${{ steps.retrieve_version.outputs.new_version }}"
      #     git push

      - name: Create release changelog
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          target-branch: ${{ github.ref_name }}
          config-file: .github/workflows/release-please-config.json
          manifest-file: .github/workflows/.release-please-manifest.json
